version: '3'
services:
  lamp-web:
    image: "httpd:2.4"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./apache2/conf/server.crt:/usr/local/apache2/conf/server.crt
    - ./apache2/conf/server.key:/usr/local/apache2/conf/server.key
    - ./apache2/logs:/usr/local/apache2/logs
    - ./htdocs:/usr/local/apache2/htdocs
  lamp-php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
    - ./htdocs:/usr/local/apache2/htdocs
  lamp-db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
    - ./mysql/data:/var/lib/mysql
